name: Lint

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.5.0

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.yarn/cache
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - name: Install dependencies
        run: yarn --immutable

      - name: Lint
        run: yarn lint
